services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
    networks:
      - my_network

  backend: 
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=tinnadech
      - MYSQL_DATABASE=user_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my_network
    volumes:
      - ./backend:/app 

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    networks:
      - my_network
    volumes:
      - ./frontend:/app

  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: tinnadech
      MYSQL_DATABASE: user_db
    ports:
      - "3306:3306"
    networks:
      - my_network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s
    
networks:
  my_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
